version: 2

sources:
  - name: raw_data
    database: raw
    schema: experienced
    tables:
      - name: stockwatch
        description: "This table contains the raw stock prices data including open, high, low, close, adjusted close, and volume."
        columns:
          - name: date
            description: "The date of the stock data."
            tests:
              - not_null
          - name: ticker
            description: "The stock ticker symbol."
            tests:
              - not_null
              - unique
          - name: open
            description: "The opening price of the stock on the trading day."
          - name: high
            description: "The highest price reached by the stock during the trading day."
          - name: low
            description: "The lowest price reached by the stock during the trading day."
          - name: close
            description: "The closing price of the stock on the trading day."
          - name: adj_close
            description: "The adjusted closing price, which accounts for corporate actions like dividends and stock splits."
          - name: volume
            description: "The total number of shares traded during the trading day."

      - name: sector_mapping # Adding the sector_mapping table
        description: "This table contains the mapping of stock tickers to sectors."
        columns:
          - name: ticker
            description: "The stock ticker symbol."
            tests:
              - not_null
              - unique
          - name: sector
            description: "The sector to which the stock belongs."
